#!/bin/bash

# Check if jq is installed
if ! command -v jq >/dev/null; then
    echo "Error: 'jq' is not installed. Please install 'jq' before running this script."
    exit 1
fi

# Function to extract the Bitbucket username from a URL
extract_username_from_url() {
    local url=$1
    local username=""
    if [[ $url =~ bitbucket\.org/([^/]+) ]]; then
        username=${BASH_REMATCH[1]}
    fi
    echo "$username"
}

# Check if the username/URL parameter is provided
if [ $# -eq 0 ]; then
    echo "Error: Bitbucket username or URL is missing."
    echo "Usage: $0 <username_or_url> [target_directory]"
    exit 1
fi

# Extract the Bitbucket username or URL from the parameter
PARAMETER="$1"
USERNAME=$(extract_username_from_url "$PARAMETER")

# Set the target directory or fallback to the current directory
TARGET_DIR="${2:-$(pwd)}"
mkdir "$TARGET_DIR" -p

if [ -z "$USERNAME" ]; then
  # The input is a username
  USERNAME="$PARAMETER"
fi

# Fetch the repository URLs using the Bitbucket API
REPO_URLS=$(curl -s "https://api.bitbucket.org/2.0/repositories/$USERNAME" | jq -r '.values[].links.clone[].href')

# Check if repositories are found
if [ -z "$REPO_URLS" ]; then
    echo "No repositories found for the Bitbucket user: $USERNAME"
    exit 1
fi

# Iterate over each repository URL
for URL in $REPO_URLS; do
    # Extract the repository name from the URL
    REPO_NAME=$(basename -s .git "$URL")
    echo
    echo "Processing '$REPO_NAME'..."
    echo "============================================"

    # Check if the directory already exists
    if [ -d "$TARGET_DIR/$REPO_NAME" ]; then
        echo "Repository '$REPO_NAME' already exists in '$TARGET_DIR'. Updating..."
        cd "$TARGET_DIR/$REPO_NAME"
        git pull
        cd "$TARGET_DIR"
        echo
    else
        echo "Cloning repository: $REPO_NAME"
        git clone "$URL" "$TARGET_DIR/$REPO_NAME"
        echo
    fi
done
