#!/bin/bash

# Function to extract the hostname from a URL
extract_hostname() {
    local url=$1
    local hostname=""

    # Extract the hostname from the URL
    if [[ $url =~ ^(https?://)?([^/]+).* ]]; then
        hostname=${BASH_REMATCH[2]}
    fi

    echo "$hostname"
}

# Check if the URL parameter is provided
if [ $# -lt 1 ]; then
    echo "Error: Repository URL is missing."
    echo "Usage: $0 <repo_url> [target_directory]"
    exit 1
fi

# Extract the hostname from the URL
URL="$1"
TARGET_DIR="$2"
HOSTNAME=$(extract_hostname "$URL")

# Check the hostname to determine the repository hosting service
case "$HOSTNAME" in
    github.com)
        ./github-clone-public-repos "$URL" "$TARGET_DIR"
        ;;
    bitbucket.org)
        ./bitbucket-clone-public-repos "$URL" "$TARGET_DIR"
        ;;
    *)
        ./gitlab-clone-public-repos "$URL" "$TARGET_DIR"
        ;;
esac
